[font]
size = 14.0

  [font.normal]
  family = "RobotoMono Nerd Font Mono"
  style = "Medium"

  [font.bold]
  family = "RobotoMono Nerd Font Mono"
  style = "Bold"

  [font.italic]
  family = "RobotoMono Nerd Font Mono"
  style = "Italic"

[window.dimensions]
columns = 120
lines = 24

[scrolling]
history = 100_000
